create table if not exists public.categorias_articulos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  slug text not null unique,
  descripcion text,
  color text not null default '#B86B4B',
  activo boolean not null default true,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categorias_articulos_nombre_not_empty check (length(trim(nombre)) > 0),
  constraint categorias_articulos_slug_format check (slug ~ '^[a-z]+(?:-[a-z]+)*$'),
  constraint categorias_articulos_color_format check (color ~ '^#[0-9A-Fa-f]{6}$')
);

alter table public.articulos
  add column if not exists categoria_id bigint;

insert into public.categorias_articulos (nombre, slug, orden)
select distinct
  trim(a.categoria),
  lower(regexp_replace(
    regexp_replace(
      translate(lower(trim(a.categoria)), 'áéíóúüñ', 'aeiouun'),
      '[^a-z0-9]+', '-', 'g'
    ),
    '(^-|-$)', '', 'g'
  )),
  0
from public.articulos a
where nullif(trim(a.categoria), '') is not null
on conflict (slug) do nothing;

update public.articulos a
set categoria_id = c.id
from public.categorias_articulos c
where a.categoria_id is null
  and c.slug = lower(regexp_replace(
    regexp_replace(
      translate(lower(trim(a.categoria)), 'áéíóúüñ', 'aeiouun'),
      '[^a-z0-9]+', '-', 'g'
    ),
    '(^-|-$)', '', 'g'
  ));

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'articulos_categoria_id_fkey'
  ) then
    alter table public.articulos
      add constraint articulos_categoria_id_fkey
      foreign key (categoria_id) references public.categorias_articulos(id)
      on delete set null;
  end if;
end $$;

alter table public.categorias_articulos enable row level security;

drop policy if exists categorias_articulos_public_read on public.categorias_articulos;
create policy categorias_articulos_public_read
on public.categorias_articulos for select
using (activo = true or public.is_editor());

drop policy if exists categorias_articulos_editor_write on public.categorias_articulos;
create policy categorias_articulos_editor_write
on public.categorias_articulos for all
to authenticated
using (public.is_editor())
with check (public.is_editor());

drop trigger if exists categorias_articulos_updated_at on public.categorias_articulos;
create trigger categorias_articulos_updated_at
before update on public.categorias_articulos
for each row execute function public.set_updated_at();

create index if not exists categorias_articulos_active_order_idx
on public.categorias_articulos (activo, orden, nombre);

create index if not exists articulos_categoria_id_idx
on public.articulos (categoria_id);
