-- Roles and publishing controls for the editorial back office.
create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'editor' check (role in ('admin', 'editor')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_roles enable row level security;

create or replace function public.current_user_role()
returns text language sql stable security definer set search_path = public
as $$ select role from public.user_roles where user_id = auth.uid() $$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select coalesce(public.current_user_role() = 'admin', false) $$;

create or replace function public.is_editor()
returns boolean language sql stable security definer set search_path = public
as $$ select coalesce(public.current_user_role() in ('admin', 'editor'), false) $$;

-- Existing content remains visible after applying the migration; new records are drafts.
do $$
declare table_name text;
begin
  foreach table_name in array array['lecturas','reflexiones','santos','oraciones','articulos'] loop
    execute format('alter table public.%I add column if not exists published boolean not null default true', table_name);
    execute format('alter table public.%I add column if not exists published_at timestamptz', table_name);
    execute format('alter table public.%I add column if not exists updated_at timestamptz not null default now()', table_name);
    execute format('create index if not exists %I on public.%I (published)', table_name || '_published_idx', table_name);
  end loop;
end $$;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'lecturas'
      and column_name = 'fecha'
  ) then
    create index if not exists lecturas_published_fecha_idx
      on public.lecturas (published, fecha);
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'reflexiones'
      and column_name = 'fecha'
  ) then
    create index if not exists reflexiones_published_fecha_idx
      on public.reflexiones (published, fecha);
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'santos'
      and column_name = 'fecha'
  ) then
    create index if not exists santos_published_fecha_idx
      on public.santos (published, fecha);
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'articulos'
      and column_name = 'fecha'
  ) then
    create index if not exists articulos_published_fecha_idx
      on public.articulos (published, fecha);
  end if;
end $$;

do $$
declare table_name text;
begin
  foreach table_name in array array['lecturas','reflexiones','santos','oraciones','articulos'] loop
    execute format('alter table public.%I alter column published set default false', table_name);
  end loop;
end $$;

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.homepage_sections (
  id bigint generated by default as identity primary key,
  section_key text not null unique,
  title text,
  content text,
  display_order integer not null default 0,
  published boolean not null default false,
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

do $$
declare table_name text;
begin
  foreach table_name in array array['user_roles','site_settings','homepage_sections','lecturas','reflexiones','santos','oraciones','articulos'] loop
    execute format('drop trigger if exists %I on public.%I', table_name || '_updated_at', table_name);
    execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()', table_name || '_updated_at', table_name);
  end loop;
end $$;

create or replace function public.set_published_at()
returns trigger language plpgsql as $$
begin
  if new.published and (
    tg_op = 'INSERT' or old.published is distinct from new.published
  ) then
    new.published_at = coalesce(new.published_at, now());
  end if;
  if not new.published then new.published_at = null; end if;
  return new;
end $$;
do $$
declare table_name text;
begin
  foreach table_name in array array['lecturas','reflexiones','santos','oraciones','articulos'] loop
    execute format('drop trigger if exists %I on public.%I', table_name || '_published_at', table_name);
    execute format('create trigger %I before insert or update on public.%I for each row execute function public.set_published_at()', table_name || '_published_at', table_name);
  end loop;
end $$;

alter table public.site_settings enable row level security;
alter table public.homepage_sections enable row level security;
do $$
declare table_name text;
begin
  foreach table_name in array array['lecturas','reflexiones','santos','oraciones','articulos'] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_public_read', table_name);
    execute format('create policy %I on public.%I for select using (published = true or public.is_editor())', table_name || '_public_read', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_editor_write', table_name);
    execute format('create policy %I on public.%I for all using (public.is_editor()) with check (public.is_editor())', table_name || '_editor_write', table_name);
  end loop;
end $$;

drop policy if exists user_roles_self_read on public.user_roles;
drop policy if exists user_roles_admin_write on public.user_roles;
create policy user_roles_self_read on public.user_roles for select using (user_id = auth.uid() or public.is_admin());
create policy user_roles_admin_write on public.user_roles for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists site_settings_public_read on public.site_settings;
drop policy if exists site_settings_admin_write on public.site_settings;
create policy site_settings_public_read on public.site_settings for select using (true);
create policy site_settings_admin_write on public.site_settings for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists homepage_sections_public_read on public.homepage_sections;
drop policy if exists homepage_sections_editor_write on public.homepage_sections;
create policy homepage_sections_public_read on public.homepage_sections for select using (published = true);
create policy homepage_sections_editor_write on public.homepage_sections for all using (public.is_editor()) with check (public.is_editor());
