-- Reusable references with explicit foreign-key relationships for every content type.
create table if not exists public.content_sources (
  id bigint generated by default as identity primary key,
  nombre text not null,
  tipo text not null,
  autor text,
  referencia text,
  url text,
  descripcion text,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint content_sources_nombre_not_empty check (length(trim(nombre)) > 0),
  constraint content_sources_tipo_check check (tipo in ('biblia', 'catecismo', 'documento_pontificio', 'concilio', 'padres_iglesia', 'codigo_derecho_canonico', 'otra'))
);

alter table public.content_sources enable row level security;
drop policy if exists content_sources_public_read on public.content_sources;
create policy content_sources_public_read on public.content_sources for select
using (activo = true or public.is_editor());
drop policy if exists content_sources_editor_write on public.content_sources;
create policy content_sources_editor_write on public.content_sources for all
to authenticated using (public.is_editor()) with check (public.is_editor());

drop trigger if exists content_sources_updated_at on public.content_sources;
create trigger content_sources_updated_at before update on public.content_sources
for each row execute function public.set_updated_at();
create index if not exists content_sources_active_type_idx on public.content_sources (activo, tipo, nombre);

do $$
declare
  table_name text;
  resource_name text;
begin
  foreach resource_name in array array['articulos', 'lecturas', 'reflexiones', 'santos', 'oraciones'] loop
    table_name := regexp_replace(resource_name, 's$', '') || '_fuentes';
    execute format(
      'create table if not exists public.%I (
        content_id bigint not null references public.%I(id) on delete cascade,
        source_id bigint not null references public.content_sources(id) on delete restrict,
        orden integer not null default 0,
        nota text,
        created_at timestamptz not null default now(),
        primary key (content_id, source_id)
      )',
      table_name, resource_name
    );
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_public_read', table_name);
    execute format(
      'create policy %I on public.%I for select using (exists (select 1 from public.%I c where c.id = content_id and (c.status = ''published'' and c.published = true and c.deleted_at is null or public.is_editor())))',
      table_name || '_public_read', table_name, resource_name
    );
    execute format('drop policy if exists %I on public.%I', table_name || '_editor_write', table_name);
    execute format(
      'create policy %I on public.%I for all using (public.is_editor()) with check (public.is_editor())',
      table_name || '_editor_write', table_name
    );
    execute format('drop policy if exists %I on public.%I', table_name || '_author_write', table_name);
    execute format(
      'create policy %I on public.%I for all using (public.is_author() and exists (select 1 from public.%I c where c.id = content_id and c.created_by = auth.uid() and c.status = ''draft'' and c.deleted_at is null)) with check (public.is_author() and exists (select 1 from public.%I c where c.id = content_id and c.created_by = auth.uid() and c.status = ''draft'' and c.deleted_at is null))',
      table_name || '_author_write', table_name, resource_name, resource_name
    );
    execute format('create index if not exists %I on public.%I (source_id)', table_name || '_source_idx', table_name);
  end loop;
end $$;
