-- Independent liturgical calendar catalog with optional content associations.
create table if not exists public.liturgical_calendar (
  id bigint generated by default as identity primary key,
  fecha date not null,
  celebracion text not null,
  tiempo_liturgico text not null,
  color_liturgico text not null default 'verde',
  grado text not null default 'feria',
  descripcion text,
  lectura_id bigint references public.lecturas(id) on delete set null,
  reflexion_id bigint references public.reflexiones(id) on delete set null,
  santo_id bigint references public.santos(id) on delete set null,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint liturgical_calendar_celebracion_not_empty check (length(trim(celebracion)) > 0),
  constraint liturgical_calendar_time_check check (tiempo_liturgico in ('adviento', 'navidad', 'cuaresma', 'pascua', 'ordinario')),
  constraint liturgical_calendar_color_check check (color_liturgico in ('verde', 'blanco', 'rojo', 'morado', 'rosa', 'dorado')),
  constraint liturgical_calendar_grade_check check (grado in ('solemnidad', 'fiesta', 'memoria', 'feria')),
  constraint liturgical_calendar_unique_celebration unique (fecha, celebracion)
);

alter table public.liturgical_calendar enable row level security;
drop policy if exists liturgical_calendar_public_read on public.liturgical_calendar;
create policy liturgical_calendar_public_read on public.liturgical_calendar for select
using (activo = true);
drop policy if exists liturgical_calendar_editor_write on public.liturgical_calendar;
create policy liturgical_calendar_editor_write on public.liturgical_calendar for all
to authenticated using (public.is_editor()) with check (public.is_editor());

drop trigger if exists liturgical_calendar_updated_at on public.liturgical_calendar;
create trigger liturgical_calendar_updated_at before update on public.liturgical_calendar
for each row execute function public.set_updated_at();

create index if not exists liturgical_calendar_date_idx
on public.liturgical_calendar (fecha, activo);
create index if not exists liturgical_calendar_time_idx
on public.liturgical_calendar (tiempo_liturgico, fecha);

drop trigger if exists liturgical_calendar_audit on public.liturgical_calendar;
create trigger liturgical_calendar_audit after insert or update or delete on public.liturgical_calendar
for each row execute function public.record_admin_audit();
