-- Record administrative changes at the database boundary.
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  table_name text not null,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint audit_log_action_check check (action in ('INSERT', 'UPDATE', 'DELETE'))
);

alter table public.audit_log enable row level security;
drop policy if exists audit_log_editor_read on public.audit_log;
create policy audit_log_editor_read on public.audit_log for select
to authenticated using (public.is_editor());

create index if not exists audit_log_created_at_idx on public.audit_log (created_at desc);
create index if not exists audit_log_actor_idx on public.audit_log (actor_user_id, created_at desc);
create index if not exists audit_log_table_record_idx on public.audit_log (table_name, record_id, created_at desc);

create or replace function public.record_admin_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  row_data jsonb;
  old_row jsonb;
  new_row jsonb;
  primary_key text;
begin
  if tg_op = 'DELETE' then
    old_row := to_jsonb(old);
    row_data := old_row;
  else
    new_row := to_jsonb(new);
    row_data := new_row;
  end if;

  primary_key := coalesce(row_data ->> 'id', row_data ->> 'content_id', row_data ->> 'user_id');

  insert into public.audit_log (actor_user_id, action, table_name, record_id, old_data, new_data, metadata)
  values (
    auth.uid(),
    tg_op,
    tg_table_name,
    primary_key,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end,
    jsonb_build_object('schema', tg_table_schema, 'trigger', tg_name)
  );
  return coalesce(new, old);
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'articulos', 'lecturas', 'reflexiones', 'santos', 'oraciones',
    'categorias_articulos', 'content_sources',
    'articulo_fuentes', 'lectura_fuentes', 'reflexione_fuentes', 'santo_fuentes', 'oracione_fuentes'
  ] loop
    if to_regclass(format('public.%I', table_name)) is null then
      continue;
    end if;
    execute format('drop trigger if exists %I on public.%I', table_name || '_audit', table_name);
    execute format(
      'create trigger %I after insert or update or delete on public.%I for each row execute function public.record_admin_audit()',
      table_name || '_audit',
      table_name
    );
  end loop;
end $$;
