-- Persistent media catalogue, privacy-conscious analytics and notification subscriptions.
create table if not exists public.media_assets (
  id bigint generated by default as identity primary key,
  storage_path text not null unique,
  public_url text not null,
  filename text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 10485760),
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists media_assets_created_at_idx on public.media_assets(created_at desc);

alter table public.media_assets enable row level security;
drop policy if exists media_assets_public_read on public.media_assets;
create policy media_assets_public_read on public.media_assets for select using (true);
drop policy if exists media_assets_editor_insert on public.media_assets;
create policy media_assets_editor_insert on public.media_assets for insert to authenticated
with check (public.is_editor() and uploaded_by = auth.uid());
drop policy if exists media_assets_admin_delete on public.media_assets;
create policy media_assets_admin_delete on public.media_assets for delete to authenticated
using (public.is_admin());

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('page_view', 'content_view', 'install')),
  path text not null check (char_length(path) between 1 and 500),
  content_type text,
  content_id bigint,
  visitor_hash text,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_path_idx on public.analytics_events(path);

alter table public.analytics_events enable row level security;
drop policy if exists analytics_events_public_insert on public.analytics_events;
create policy analytics_events_public_insert on public.analytics_events for insert
with check (char_length(path) between 1 and 500);
drop policy if exists analytics_events_editor_read on public.analytics_events;
create policy analytics_events_editor_read on public.analytics_events for select to authenticated
using (public.is_editor());

create table if not exists public.notification_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique check (char_length(endpoint) between 10 and 2048),
  subscription jsonb not null,
  user_id uuid references auth.users(id) on delete set null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists notification_subscriptions_enabled_idx
  on public.notification_subscriptions(enabled) where enabled = true;

alter table public.notification_subscriptions enable row level security;
drop policy if exists notification_subscriptions_public_insert on public.notification_subscriptions;
create policy notification_subscriptions_public_insert on public.notification_subscriptions for insert
with check (user_id is null or user_id = auth.uid());
drop policy if exists notification_subscriptions_owner_update on public.notification_subscriptions;
create policy notification_subscriptions_owner_update on public.notification_subscriptions for update
using (user_id is null or user_id = auth.uid())
with check (user_id is null or user_id = auth.uid());
drop policy if exists notification_subscriptions_admin_read on public.notification_subscriptions;
create policy notification_subscriptions_admin_read on public.notification_subscriptions for select to authenticated
using (public.is_admin());

create or replace function public.publish_scheduled_content()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  total integer := 0;
  table_name text;
  affected integer;
begin
  foreach table_name in array array['lecturas', 'reflexiones', 'santos', 'oraciones', 'articulos'] loop
    execute format(
      'update public.%I set status = ''published'', published = true, published_at = coalesce(published_at, now()), scheduled_at = null where status = ''scheduled'' and scheduled_at <= now() and deleted_at is null',
      table_name
    );
    get diagnostics affected = row_count;
    total := total + affected;
  end loop;
  return total;
end;
$$;

revoke all on function public.publish_scheduled_content() from public;
grant execute on function public.publish_scheduled_content() to service_role;
